apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: delegate-to-opa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      security: zta-enabled
  action: CUSTOM
  provider:
    name: {{ .Values.istio.extensionProviderName }}
  rules:
    - {}
