{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    {{- include "opa.labels" . | nindent 4 }}
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
        {{- include "opa.labels" . | nindent 8 }}
    spec:
      containers:
        - name: opa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "run"
            - "--server"
            - "--v0-compatible"
            - "--addr=0.0.0.0:{{ .Values.httpPort }}"
            - "--diagnostic-addr=0.0.0.0:{{ .Values.diagnosticPort }}"
            - "--set=plugins.envoy_ext_authz_grpc.addr=:{{ .Values.grpcPort }}"
            - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"
            - "--set=decision_logs.console=true"
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
            - name: grpc
              containerPort: {{ .Values.grpcPort }}
            - name: diagnostic
              containerPort: {{ .Values.diagnosticPort }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: diagnostic
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: diagnostic
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
