{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    {{- include "opa.labels" . | nindent 4 }}
    app: opa
spec:
  selector:
    app: opa
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: grpc
{{- end }}
